name: Security checks

on:
  workflow_run:
    workflows:
      - "CI Pipeline"
    types:
      - completed
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 3 * * 0" # weekly

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: CodeQL (SAST)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3

  dependency-review:
    # Run on manual dispatch or when a CI workflow_run finished successfully *and* it references a PR
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests != null && github.event.workflow_run.pull_requests[0] != null) }}
    name: Dependency review (PR delta)
    runs-on: ubuntu-latest
    needs: codeql
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency review
        uses: actions/dependency-review-action@v4
        with:
          # Provide PR base/head refs when triggered via workflow_run
          base-ref: ${{ github.event.workflow_run.pull_requests[0].base.ref }}
          head-ref: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
          fail-on-severity: high

  npm-audit:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: npm audit (fail on high)
    runs-on: ubuntu-latest
    needs: dependency-review
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit and fail on high/critical
        run: npm audit --audit-level=high

  eslint:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: ESLint (static lint)
    runs-on: ubuntu-latest
    needs: [codeql, npm-audit]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version:
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (fail on warnings)
        run: npx eslint . --ext .js,.mjs --max-warnings=0
