name: Security checks

on:
  workflow_run:
    workflows:
      - "CI Pipeline"
    types:
      - completed
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 3 * * 0" # weekly

permissions:
  contents: read
  security-events: write

jobs:
  codeql:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    name: CodeQL (SAST)
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3

  owasp-dependency-check:
    if: ${{ always() && (github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success') }}
    name: OWASP Dependency-Check (scan & fail on CVSS >= 7)
    runs-on: ubuntu-latest
    needs: codeql
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run OWASP Dependency-Check (Docker)
        run: |
          mkdir -p "${{ github.workspace }}/dependency-check-report"
          docker run --rm \
            -v "${{ github.workspace }}:/src" \
            -v "${{ github.workspace }}/dependency-check-report:/report" \
            owasp/dependency-check:latest \
            --project "stock-app" \
            --scan /src \
            --format ALL \
            --out /report \
            --failOnCVSS 7

      - name: Upload Dependency-Check reports
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report

  dependency-review:
    if: ${{ always() && (github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests != null && github.event.workflow_run.pull_requests[0] != null)) }}
    name: Dependency review (PR delta)
    runs-on: ubuntu-latest
    needs: owasp-dependency-check
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Dependency review
        uses: actions/dependency-review-action@v4
        with:
          base-ref: ${{ github.event.workflow_run.pull_requests[0].base.ref }}
          head-ref: ${{ github.event.workflow_run.pull_requests[0].head.ref }}
          fail-on-severity: high

  npm-audit:
    if: ${{ always() && (github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success') }}
    name: npm audit (fail on high)
    runs-on: ubuntu-latest
    needs: dependency-review
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit and fail on high/critical
        run: npm audit --audit-level=high

  eslint:
    if: ${{ always() && (github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success') }}
    name: ESLint (static lint)
    runs-on: ubuntu-latest
    needs: npm-audit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.17.0
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (fail on warnings)
        run: npx eslint . --ext .js,.mjs --max-warnings=0
